version: '3.5'
services:
  api:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512MB'
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pessoas_db
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1GB'
